In [1]:
!pip install ipython-sql

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Requirement already satisfied: sqlparse in c:\users\microsoft\anaconda3\lib\site-packages (from ipython-sql) (0.4.4)
Collecting prettytable
  Downloading prettytable-3.7.0-py3-none-any.whl (27 kB)
Requirement already satisfied: six in c:\users\microsoft\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython in c:\users\microsoft\anaconda3\lib\site-packages (from ipython-sql) (7.31.1)
Collecting sqlalchemy>=2.0
  Using cached SQLAlchemy-2.0.12-cp39-cp39-win_amd64.whl (2.0 MB)
Requirement already satisfied: ipython-genutils in c:\users\microsoft\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\microsoft\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\microsoft\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.3.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: traitlets>=4.2 in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: decorator in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: pickleshare in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: matplotlib-inline in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: colorama in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.5)
Requirement already satisfied: pygments in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: setuptools>=18.5 in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (63.4.1)
Requirement already satisfied: jedi>=0.16 in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: backcall in c:\users\microsoft\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\microsoft\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\microsoft\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Installing collected packages: sqlalchemy, prettytable, ipython-sql
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.39
    Uninstalling SQLAlchemy-1.4.39:
      Successfully uninstalled SQLAlchemy-1.4.39
Successfully installed ipython-sql-0.5.0 prettytable-3.7.0 sqlalchemy-2.0.12

In [ ]:
!pip install PyMySQL

In [18]:
import sqlalchemy
import pymysql

pymysql.install_as_MySQLdb()

engine = sqlalchemy.create_engine('mysql+mysqldb://root:sanaz11@covid') # connect to server

In [78]:
%load_ext sql

# Connect to the database
%sql  mysql://root:sanaz11@localhost:3306/classicmodels

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [79]:
%config SqlMagic.displaycon = False

In [80]:
%sql select * from orders

326 rows affected.

[(10100, datetime.date(2022, 2, 1), datetime.date(2003, 1, 13), datetime.date(2003, 1, 10), 'Shipped', None, 363, 20),
 (10101, datetime.date(2022, 3, 1), datetime.date(2003, 1, 18), datetime.date(2003, 1, 11), 'Shipped', 'Check on availability.', 128, 20),
 (10102, datetime.date(2022, 2, 1), datetime.date(2003, 1, 18), datetime.date(2003, 1, 14), 'Shipped', None, 181, 20),
 (10103, datetime.date(2022, 3, 8), datetime.date(2003, 2, 7), datetime.date(2003, 2, 2), 'Shipped', None, 121, 20),
 (10104, datetime.date(2003, 1, 31), datetime.date(2003, 2, 9), datetime.date(2003, 2, 1), 'Shipped', None, 141, 20),
 (10105, datetime.date(2003, 2, 11), datetime.date(2003, 2, 21), datetime.date(2003, 2, 12), 'Shipped', None, 145, 20),
 (10106, datetime.date(2003, 2, 17), datetime.date(2003, 2, 24), datetime.date(2003, 2, 21), 'Shipped', None, 278, 20),
 (10107, datetime.date(2003, 2, 24), datetime.date(2003, 3, 3), datetime.date(2003, 2, 26), 'Shipped', 'Difficult to negotiate with customer. We need more marketing materials', 131, 20),
 (10108, datetime.date(2003, 3, 3), datetime.date(2003, 3, 12), datetime.date(2003, 3, 8), 'Shipped', None, 385, 20),
 (10109, datetime.date(2003, 3, 10), datetime.date(2003, 3, 19), datetime.date(2003, 3, 11), 'Shipped', 'Customer requested that FedEx Ground is used for this shipping', 486, 20),
 (10110, datetime.date(2003, 3, 18), datetime.date(2003, 3, 24), datetime.date(2003, 3, 20), 'Shipped', None, 187, 20),
 (10111, datetime.date(2003, 3, 25), datetime.date(2003, 3, 31), datetime.date(2003, 3, 30), 'Shipped', None, 129, 20),
 (10112, datetime.date(2003, 3, 24), datetime.date(2003, 4, 3), datetime.date(2003, 3, 29), 'Shipped', 'Customer requested that ad materials (such as posters, pamphlets) be included in the shippment', 144, 20),
 (10113, datetime.date(2003, 3, 26), datetime.date(2003, 4, 2), datetime.date(2003, 3, 27), 'Shipped', None, 124, 20),
 (10114, datetime.date(2003, 4, 1), datetime.date(2003, 4, 7), datetime.date(2003, 4, 2), 'Shipped', None, 172, 20),
 (10115, datetime.date(2003, 4, 4), datetime.date(2003, 4, 12), datetime.date(2003, 4, 7), 'Shipped', None, 424, 20),
 (10116, datetime.date(2003, 4, 11), datetime.date(2003, 4, 19), datetime.date(2003, 4, 13), 'Shipped', None, 381, 20),
 (10117, datetime.date(2003, 4, 16), datetime.date(2003, 4, 24), datetime.date(2003, 4, 17), 'Shipped', None, 148, 20),
 (10118, datetime.date(2003, 4, 21), datetime.date(2003, 4, 29), datetime.date(2003, 4, 26), 'Shipped', 'Customer has worked with some of our vendors in the past and is aware of their MSRP', 216, 20),
 (10119, datetime.date(2003, 4, 28), datetime.date(2003, 5, 5), datetime.date(2003, 5, 2), 'Shipped', None, 382, 20),
 (10120, datetime.date(2003, 4, 29), datetime.date(2003, 5, 8), datetime.date(2003, 5, 1), 'Shipped', None, 114, 20),
 (10121, datetime.date(2003, 5, 7), datetime.date(2003, 5, 13), datetime.date(2003, 5, 13), 'Shipped', None, 353, 20),
 (10122, datetime.date(2003, 5, 8), datetime.date(2003, 5, 16), datetime.date(2003, 5, 13), 'Shipped', None, 350, 20),
 (10123, datetime.date(2003, 5, 20), datetime.date(2003, 5, 29), datetime.date(2003, 5, 22), 'Shipped', None, 103, 20),
 (10124, datetime.date(2003, 5, 21), datetime.date(2003, 5, 29), datetime.date(2003, 5, 25), 'Shipped', 'Customer very concerned about the exact color of the models. There is high risk that he may dispute the order because there is a slight color mismatch', 112, 20),
 (10125, datetime.date(2003, 5, 21), datetime.date(2003, 5, 27), datetime.date(2003, 5, 24), 'Shipped', None, 114, 20),
 (10126, datetime.date(2003, 5, 28), datetime.date(2003, 6, 7), datetime.date(2003, 6, 2), 'Shipped', None, 458, 20),
 (10127, datetime.date(2003, 6, 3), datetime.date(2003, 6, 9), datetime.date(2003, 6, 6), 'Shipped', 'Customer requested special shippment. The instructions were passed along to the warehouse', 151, 20),
 (10128, datetime.date(2003, 6, 6), datetime.date(2003, 6, 12), datetime.date(2003, 6, 11), 'Shipped', None, 141, 20),
 (10129, datetime.date(2003, 6, 12), datetime.date(2003, 6, 18), datetime.date(2003, 6, 14), 'Shipped', None, 324, 20),
 (10130, datetime.date(2003, 6, 16), datetime.date(2003, 6, 24), datetime.date(2003, 6, 21), 'Shipped', None, 198, 20),
 (10131, datetime.date(2003, 6, 16), datetime.date(2003, 6, 25), datetime.date(2003, 6, 21), 'Shipped', None, 447, 20),
 (10132, datetime.date(2003, 6, 25), datetime.date(2003, 7, 1), datetime.date(2003, 6, 28), 'Shipped', None, 323, 20),
 (10133, datetime.date(2003, 6, 27), datetime.date(2003, 7, 4), datetime.date(2003, 7, 3), 'Shipped', None, 141, 20),
 (10134, datetime.date(2003, 7, 1), datetime.date(2003, 7, 10), datetime.date(2003, 7, 5), 'Shipped', None, 250, 20),
 (10135, datetime.date(2003, 7, 2), datetime.date(2003, 7, 12), datetime.date(2003, 7, 3), 'Shipped', None, 124, 20),
 (10136, datetime.date(2003, 7, 4), datetime.date(2003, 7, 14), datetime.date(2003, 7, 6), 'Shipped', 'Customer is interested in buying more Ferrari models', 242, 20),
 (10137, datetime.date(2003, 7, 10), datetime.date(2003, 7, 20), datetime.date(2003, 7, 14), 'Shipped', None, 353, 20),
 (10138, datetime.date(2003, 7, 7), datetime.date(2003, 7, 16), datetime.date(2003, 7, 13), 'Shipped', None, 496, 20),
 (10139, datetime.date(2003, 7, 16), datetime.date(2003, 7, 23), datetime.date(2003, 7, 21), 'Shipped', None, 282, 20),
 (10140, datetime.date(2003, 7, 24), datetime.date(2003, 8, 2), datetime.date(2003, 7, 30), 'Shipped', None, 161, 20),
 (10141, datetime.date(2003, 8, 1), datetime.date(2003, 8, 9), datetime.date(2003, 8, 4), 'Shipped', None, 334, 20),
 (10142, datetime.date(2003, 8, 8), datetime.date(2003, 8, 16), datetime.date(2003, 8, 13), 'Shipped', None, 124, 20),
 (10143, datetime.date(2003, 8, 10), datetime.date(2003, 8, 18), datetime.date(2003, 8, 12), 'Shipped', 'Can we deliver the new Ford Mustang models by end-of-quarter?', 320, 20),
 (10144, datetime.date(2003, 8, 13), datetime.date(2003, 8, 21), datetime.date(2003, 8, 14), 'Shipped', None, 381, 20),
 (10145, datetime.date(2003, 8, 25), datetime.date(2003, 9, 2), datetime.date(2003, 8, 31), 'Shipped', None, 205, 20),
 (10146, datetime.date(2003, 9, 3), datetime.date(2003, 9, 13), datetime.date(2003, 9, 6), 'Shipped', None, 447, 20),
 (10147, datetime.date(2003, 9, 5), datetime.date(2003, 9, 12), datetime.date(2003, 9, 9), 'Shipped', None, 379, 20),
 (10148, datetime.date(2003, 9, 11), datetime.date(2003, 9, 21), datetime.date(2003, 9, 15), 'Shipped', 'They want to reevaluate their terms agreement with Finance.', 276, 20),
 (10149, datetime.date(2003, 9, 12), datetime.date(2003, 9, 18), datetime.date(2003, 9, 17), 'Shipped', None, 487, 20),
 (10150, datetime.date(2003, 9, 19), datetime.date(2003, 9, 27), datetime.date(2003, 9, 21), 'Shipped', 'They want to reevaluate their terms agreement with Finance.', 148, 20),
 (10151, datetime.date(2003, 9, 21), datetime.date(2003, 9, 30), datetime.date(2003, 9, 24), 'Shipped', None, 311, 20),
 (10152, datetime.date(2003, 9, 25), datetime.date(2003, 10, 3), datetime.date(2003, 10, 1), 'Shipped', None, 333, 20),
 (10153, datetime.date(2003, 9, 28), datetime.date(2003, 10, 5), datetime.date(2003, 10, 3), 'Shipped', None, 141, 20),
 (10154, datetime.date(2003, 10, 2), datetime.date(2003, 10, 12), datetime.date(2003, 10, 8), 'Shipped', None, 219, 20),
 (10155, datetime.date(2003, 10, 6), datetime.date(2003, 10, 13), datetime.date(2003, 10, 7), 'Shipped', None, 186, 20),
 (10156, datetime.date(2003, 10, 8), datetime.date(2003, 10, 17), datetime.date(2003, 10, 11), 'Shipped', None, 141, 20),
 (10157, datetime.date(2003, 10, 9), datetime.date(2003, 10, 15), datetime.date(2003, 10, 14), 'Shipped', None, 473, 20),
 (10158, datetime.date(2022, 3, 8), datetime.date(2003, 10, 18), datetime.date(2003, 10, 15), 'Shipped', None, 121, 20),
 (10159, datetime.date(2003, 10, 10), datetime.date(2003, 10, 19), datetime.date(2003, 10, 16), 'Shipped', None, 321, 20),
 (10160, datetime.date(2003, 10, 11), datetime.date(2003, 10, 17), datetime.date(2003, 10, 17), 'Shipped', None, 347, 20),
 (10161, datetime.date(2003, 10, 17), datetime.date(2003, 10, 25), datetime.date(2003, 10, 20), 'Shipped', None, 227, 20),
 (10162, datetime.date(2003, 10, 18), datetime.date(2003, 10, 26), datetime.date(2003, 10, 19), 'Shipped', None, 321, 20),
 (10163, datetime.date(2003, 10, 20), datetime.date(2003, 10, 27), datetime.date(2003, 10, 24), 'Shipped', None, 424, 20),
 (10164, datetime.date(2003, 10, 21), datetime.date(2003, 10, 30), datetime.date(2003, 10, 23), 'Resolved', "This order was disputed, but resolved on 11/1/2003; Customer doesn't like the colors and precision of the models.", 452, 20),
 (10165, datetime.date(2003, 10, 22), datetime.date(2003, 10, 31), datetime.date(2003, 12, 26), 'Shipped', "This order was on hold because customers's credit limit had been exceeded. Order will ship when payment is received", 148, 20),
 (10166, datetime.date(2003, 10, 21), datetime.date(2003, 10, 30), datetime.date(2003, 10, 27), 'Shipped', None, 462, 20),
 (10167, datetime.date(2003, 10, 23), datetime.date(2003, 10, 30), None, 'Cancelled', "Customer called to cancel. The warehouse was notified in time and the order didn't ship. They have a new VP of Sales and are shifting their sales model. Our VP of Sales should contact them.", 448, 20),
 (10168, datetime.date(2003, 10, 28), datetime.date(2003, 11, 3), datetime.date(2003, 11, 1), 'Shipped', None, 161, 20),
 (10169, datetime.date(2003, 11, 4), datetime.date(2003, 11, 14), datetime.date(2003, 11, 9), 'Shipped', None, 276, 20),
 (10170, datetime.date(2003, 11, 4), datetime.date(2003, 11, 12), datetime.date(2003, 11, 7), 'Shipped', None, 452, 20),
 (10171, datetime.date(2003, 11, 5), datetime.date(2003, 11, 13), datetime.date(2003, 11, 7), 'Shipped', None, 233, 20),
 (10172, datetime.date(2003, 11, 5), datetime.date(2003, 11, 14), datetime.date(2003, 11, 11), 'Shipped', None, 175, 20),
 (10173, datetime.date(2003, 11, 5), datetime.date(2003, 11, 15), datetime.date(2003, 11, 9), 'Shipped', 'Cautious optimism. We have happy customers here, if we can keep them well stocked.  I need all the information I can get on the planned shippments of Porches', 278, 20),
 (10174, datetime.date(2003, 11, 6), datetime.date(2003, 11, 15), datetime.date(2003, 11, 10), 'Shipped', None, 333, 20),
 (10175, datetime.date(2003, 11, 6), datetime.date(2003, 11, 14), datetime.date(2003, 11, 9), 'Shipped', None, 324, 20),
 (10176, datetime.date(2003, 11, 6), datetime.date(2003, 11, 15), datetime.date(2003, 11, 12), 'Shipped', None, 386, 20),
 (10177, datetime.date(2003, 11, 7), datetime.date(2003, 11, 17), datetime.date(2003, 11, 12), 'Shipped', None, 344, 20),
 (10178, datetime.date(2003, 11, 8), datetime.date(2003, 11, 16), datetime.date(2003, 11, 10), 'Shipped', 'Custom shipping instructions sent to warehouse', 242, 20),
 (10179, datetime.date(2003, 11, 11), datetime.date(2003, 11, 17), datetime.date(2003, 11, 13), 'Cancelled', 'Customer cancelled due to urgent budgeting issues. Must be cautious when dealing with them in the future. Since order shipped already we must discuss who would cover the shipping charges.', 496, 20),
 (10180, datetime.date(2003, 11, 11), datetime.date(2003, 11, 19), datetime.date(2003, 11, 14), 'Shipped', None, 171, 20),
 (10181, datetime.date(2003, 11, 12), datetime.date(2003, 11, 19), datetime.date(2003, 11, 15), 'Shipped', None, 167, 20),
 (10182, datetime.date(2003, 11, 12), datetime.date(2003, 11, 21), datetime.date(2003, 11, 18), 'Shipped', None, 124, 20),
 (10183, datetime.date(2003, 11, 13), datetime.date(2003, 11, 22), datetime.date(2003, 11, 15), 'Shipped', 'We need to keep in close contact with their Marketing VP. He is the decision maker for all their purchases.', 339, 20),
 (10184, datetime.date(2003, 11, 14), datetime.date(2003, 11, 22), datetime.date(2003, 11, 20), 'Shipped', None, 484, 20),
 (10185, datetime.date(2003, 11, 14), datetime.date(2003, 11, 21), datetime.date(2003, 11, 20), 'Shipped', None, 320, 20),
 (10186, datetime.date(2003, 11, 14), datetime.date(2003, 11, 20), datetime.date(2003, 11, 18), 'Shipped', 'They want to reevaluate their terms agreement with the VP of Sales', 489, 20),
 (10187, datetime.date(2003, 11, 15), datetime.date(2003, 11, 24), datetime.date(2003, 11, 16), 'Shipped', None, 211, 20),
 (10188, datetime.date(2003, 11, 18), datetime.date(2003, 11, 26), datetime.date(2003, 11, 24), 'Shipped', None, 167, 20),
 (10189, datetime.date(2003, 11, 18), datetime.date(2003, 11, 25), datetime.date(2003, 11, 24), 'Shipped', 'They want to reevaluate their terms agreement with Finance.', 205, 20),
 (10190, datetime.date(2003, 11, 19), datetime.date(2003, 11, 29), datetime.date(2003, 11, 20), 'Shipped', None, 141, 20),
 (10191, datetime.date(2003, 11, 20), datetime.date(2003, 11, 30), datetime.date(2003, 11, 24), 'Shipped', 'We must be cautions with this customer. Their VP of Sales resigned. Company may be heading down.', 259, 20),
 (10192, datetime.date(2003, 11, 20), datetime.date(2003, 11, 29), datetime.date(2003, 11, 25), 'Shipped', None, 363, 20),
 (10193, datetime.date(2003, 11, 21), datetime.date(2003, 11, 28), datetime.date(2003, 11, 27), 'Shipped', None, 471, 20),
 (10194, datetime.date(2003, 11, 25), datetime.date(2003, 12, 2), datetime.date(2003, 11, 26), 'Shipped', None, 146, 20),
 (10195, datetime.date(2003, 11, 25), datetime.date(2003, 12, 1), datetime.date(2003, 11, 28), 'Shipped', None, 319, 20),
 (10196, datetime.date(2003, 11, 26), datetime.date(2003, 12, 3), datetime.date(2003, 12, 1), 'Shipped', None, 455, 20),
 (10197, datetime.date(2003, 11, 26), datetime.date(2003, 12, 2), datetime.date(2003, 12, 1), 'Shipped', 'Customer inquired about remote controlled models and gold models.', 216, 20),
 (10198, datetime.date(2003, 11, 27), datetime.date(2003, 12, 6), datetime.date(2003, 12, 3), 'Shipped', None, 385, 20),
 (10199, datetime.date(2003, 12, 1), datetime.date(2003, 12, 10), datetime.date(2003, 12, 6), 'Shipped', None, 475, 20),
 (10200, datetime.date(2003, 12, 1), datetime.date(2003, 12, 9), datetime.date(2003, 12, 6), 'Shipped', None, 211, 20),
 (10201, datetime.date(2003, 12, 1), datetime.date(2003, 12, 11), datetime.date(2003, 12, 2), 'Shipped', None, 129, 20),
 (10202, datetime.date(2003, 12, 2), datetime.date(2003, 12, 9), datetime.date(2003, 12, 6), 'Shipped', None, 357, 20),
 (10203, datetime.date(2003, 12, 2), datetime.date(2003, 12, 11), datetime.date(2003, 12, 7), 'Shipped', None, 141, 20),
 (10204, datetime.date(2003, 12, 2), datetime.date(2003, 12, 10), datetime.date(2003, 12, 4), 'Shipped', None, 151, 20),
 (10205, datetime.date(2003, 12, 3), datetime.date(2003, 12, 9), datetime.date(2003, 12, 7), 'Shipped', ' I need all the information I can get on our competitors.', 141, 20),
 (10206, datetime.date(2003, 12, 5), datetime.date(2003, 12, 13), datetime.date(2003, 12, 8), 'Shipped', 'Can we renegotiate this one?', 202, 20),
 (10207, datetime.date(2003, 12, 9), datetime.date(2003, 12, 17), datetime.date(2003, 12, 11), 'Shipped', 'Check on availability.', 495, 20),
 (10208, datetime.date(2004, 1, 2), datetime.date(2004, 1, 11), datetime.date(2004, 1, 4), 'Shipped', None, 146, 19),
 (10209, datetime.date(2004, 1, 9), datetime.date(2004, 1, 15), datetime.date(2004, 1, 12), 'Shipped', None, 347, 19),
 (10210, datetime.date(2004, 1, 12), datetime.date(2004, 1, 22), datetime.date(2004, 1, 20), 'Shipped', None, 177, 19),
 (10211, datetime.date(2004, 1, 15), datetime.date(2004, 1, 25), datetime.date(2004, 1, 18), 'Shipped', None, 406, 19),
 (10212, datetime.date(2004, 1, 16), datetime.date(2004, 1, 24), datetime.date(2004, 1, 18), 'Shipped', None, 141, 19),
 (10213, datetime.date(2004, 1, 22), datetime.date(2004, 1, 28), datetime.date(2004, 1, 27), 'Shipped', 'Difficult to negotiate with customer. We need more marketing materials', 489, 19),
 (10214, datetime.date(2004, 1, 26), datetime.date(2004, 2, 4), datetime.date(2004, 1, 29), 'Shipped', None, 458, 19),
 (10215, datetime.date(2004, 1, 29), datetime.date(2004, 2, 8), datetime.date(2004, 2, 1), 'Shipped', 'Customer requested that FedEx Ground is used for this shipping', 475, 19),
 (10216, datetime.date(2004, 2, 2), datetime.date(2004, 2, 10), datetime.date(2004, 2, 4), 'Shipped', None, 256, 19),
 (10217, datetime.date(2004, 2, 4), datetime.date(2004, 2, 14), datetime.date(2004, 2, 6), 'Shipped', None, 166, 19),
 (10218, datetime.date(2004, 2, 9), datetime.date(2004, 2, 16), datetime.date(2004, 2, 11), 'Shipped', 'Customer requested that ad materials (such as posters, pamphlets) be included in the shippment', 473, 19),
 (10219, datetime.date(2004, 2, 10), datetime.date(2004, 2, 17), datetime.date(2004, 2, 12), 'Shipped', None, 487, 19),
 (10220, datetime.date(2004, 2, 12), datetime.date(2004, 2, 19), datetime.date(2004, 2, 16), 'Shipped', None, 189, 19),
 (10221, datetime.date(2004, 2, 18), datetime.date(2004, 2, 26), datetime.date(2004, 2, 19), 'Shipped', None, 314, 19),
 (10222, datetime.date(2004, 2, 19), datetime.date(2004, 2, 27), datetime.date(2004, 2, 20), 'Shipped', None, 239, 19),
 (10223, datetime.date(2004, 2, 20), datetime.date(2004, 2, 29), datetime.date(2004, 2, 24), 'Shipped', None, 114, 19),
 (10224, datetime.date(2004, 2, 21), datetime.date(2004, 3, 2), datetime.date(2004, 2, 26), 'Shipped', 'Customer has worked with some of our vendors in the past and is aware of their MSRP', 171, 19),
 (10225, datetime.date(2004, 2, 22), datetime.date(2004, 3, 1), datetime.date(2004, 2, 24), 'Shipped', None, 298, 19),
 (10226, datetime.date(2004, 2, 26), datetime.date(2004, 3, 6), datetime.date(2004, 3, 2), 'Shipped', None, 239, 19),
 (10227, datetime.date(2004, 3, 2), datetime.date(2004, 3, 12), datetime.date(2004, 3, 8), 'Shipped', None, 146, 19),
 (10228, datetime.date(2004, 3, 10), datetime.date(2004, 3, 18), datetime.date(2004, 3, 13), 'Shipped', None, 173, 19),
 (10229, datetime.date(2004, 3, 11), datetime.date(2004, 3, 20), datetime.date(2004, 3, 12), 'Shipped', None, 124, 19),
 (10230, datetime.date(2004, 3, 15), datetime.date(2004, 3, 24), datetime.date(2004, 3, 20), 'Shipped', 'Customer very concerned about the exact color of the models. There is high risk that he may dispute the order because there is a slight color mismatch', 128, 19),
 (10231, datetime.date(2004, 3, 19), datetime.date(2004, 3, 26), datetime.date(2004, 3, 25), 'Shipped', None, 344, 19),
 (10232, datetime.date(2004, 3, 20), datetime.date(2004, 3, 30), datetime.date(2004, 3, 25), 'Shipped', None, 240, 19),
 (10233, datetime.date(2004, 3, 29), datetime.date(2004, 4, 4), datetime.date(2004, 4, 2), 'Shipped', 'Customer requested special shippment. The instructions were passed along to the warehouse', 328, 19),
 (10234, datetime.date(2004, 3, 30), datetime.date(2004, 4, 5), datetime.date(2004, 4, 2), 'Shipped', None, 412, 19),
 (10235, datetime.date(2004, 4, 2), datetime.date(2004, 4, 12), datetime.date(2004, 4, 6), 'Shipped', None, 260, 19),
 (10236, datetime.date(2004, 4, 3), datetime.date(2004, 4, 11), datetime.date(2004, 4, 8), 'Shipped', None, 486, 19),
 (10237, datetime.date(2004, 4, 5), datetime.date(2004, 4, 12), datetime.date(2004, 4, 10), 'Shipped', None, 181, 19),
 (10238, datetime.date(2004, 4, 9), datetime.date(2004, 4, 16), datetime.date(2004, 4, 10), 'Shipped', None, 145, 19),
 (10239, datetime.date(2004, 4, 12), datetime.date(2004, 4, 21), datetime.date(2004, 4, 17), 'Shipped', None, 311, 19),
 (10240, datetime.date(2004, 4, 13), datetime.date(2004, 4, 20), datetime.date(2004, 4, 20), 'Shipped', None, 177, 19),
 (10241, datetime.date(2004, 4, 13), datetime.date(2004, 4, 20), datetime.date(2004, 4, 19), 'Shipped', None, 209, 19),
 (10242, datetime.date(2004, 4, 20), datetime.date(2004, 4, 28), datetime.date(2004, 4, 25), 'Shipped', 'Customer is interested in buying more Ferrari models', 456, 19),
 (10243, datetime.date(2004, 4, 26), datetime.date(2004, 5, 3), datetime.date(2004, 4, 28), 'Shipped', None, 495, 19),

# Create Trigger

In [81]:
%sql DROP TABLE info_order

0 rows affected.

[]

In [82]:
%sql CREATE TABLE info_order(id int PRIMARY KEY auto_increment, date CHAR(50))

0 rows affected.

[]

In [83]:
%sql DROP TRIGGER after_orders_update

0 rows affected.

[]

In [84]:
%%sql 
CREATE TRIGGER after_orders_update
AFTER UPDATE ON orders
FOR EACH ROW
BEGIN
INSERT INTO info_order(date) VALUES(NOW());
END

0 rows affected.

[]

In [85]:
%sql select * from orders WHERE customerNumber=121 limit 2

2 rows affected.

[(10103, datetime.date(2022, 3, 8), datetime.date(2003, 2, 7), datetime.date(2003, 2, 2), 'Shipped', None, 121, 20),
 (10158, datetime.date(2022, 3, 8), datetime.date(2003, 10, 18), datetime.date(2003, 10, 15), 'Shipped', None, 121, 20)]

In [86]:
%sql UPDATE orders SET orderDate='2022-03-08' WHERE customerNumber=121

4 rows affected.

[]

In [87]:
%sql SELECT * FROM info_order

4 rows affected.

[(1, '2023-05-10 15:26:35'),
 (2, '2023-05-10 15:26:35'),
 (3, '2023-05-10 15:26:35'),
 (4, '2023-05-10 15:26:35')]

# Create procedure

In [98]:
%%sql
DROP PROCEDURE insert_column;

ALTER TABLE payments
DROP COLUMN year_past;

0 rows affected.
0 rows affected.

[]

In [99]:
%sql SELECT * FROM payments limit 4

4 rows affected.

[(103, 'HQ336336', datetime.date(2004, 10, 19), Decimal('6066.78')),
 (103, 'JM555205', datetime.date(2003, 6, 5), Decimal('14571.44')),
 (103, 'OM314933', datetime.date(2004, 12, 18), Decimal('1676.14')),
 (112, 'BO864823', datetime.date(2004, 12, 17), Decimal('14191.12'))]

In [100]:
%%sql
CREATE PROCEDURE insert_column()#without input and output
BEGIN
    ALTER TABLE payments
    ADD COLUMN year_past INT;
    
    UPDATE payments SET year_past=YEAR(NOW())-YEAR(paymentDate);
END

0 rows affected.

[]

In [101]:
%%sql

CALL insert_column()

273 rows affected.

[]

In [102]:
%sql SELECT * FROM payments limit 4

4 rows affected.

[(103, 'HQ336336', datetime.date(2004, 10, 19), Decimal('6066.78'), 19),
 (103, 'JM555205', datetime.date(2003, 6, 5), Decimal('14571.44'), 20),
 (103, 'OM314933', datetime.date(2004, 12, 18), Decimal('1676.14'), 19),
 (112, 'BO864823', datetime.date(2004, 12, 17), Decimal('14191.12'), 19)]

In [112]:
%%sql
DROP PROCEDURE testprocedure;


CREATE PROCEDURE testprocedure(In id INTEGER, OUT col INTEGER)
    BEGIN
     SELECT e1.firstName as name, e1.lastName as family, e2.firstName , e2.lastName  
         from employees as e1
            LEFT JOIN employees as e2 
        on e2.employeeNumber = e1.reportsTo
        WHERE e1.employeeNumber = id;
    END

0 rows affected.
0 rows affected.

[]

In [113]:
%sql SET @col=""
%sql CALL testprocedure(1002, @col)

(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
[SQL: SET @col=]
(Background on this error at: https://sqlalche.me/e/20/f405)
1 rows affected.

[('Diane', 'Murphy', None, None)]

# Create transaction

In [114]:
%%sql 
START TRANSACTION ;
select * from orders;
UPDATE test3 SET number_year=100 where name='ddd';
COMMIT;

0 rows affected.
326 rows affected.
1 rows affected.
0 rows affected.

[]